In [ ]:
import numpy as np

In [5]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
l=range(100)
%timeit [i**2 for i in l]

12.5 μs ± 2.33 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [11]:
a=np.arange(100)
%timeit a**2

1.6 μs ± 572 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# CREAT ARRAYS

In [ ]:
# MARKDOWN(in code block) > # WRITE ANYTHING> SHIFT+ENTER (to create heading)

In [16]:
a = np.array([1,2,3,4]) #one dimention
print(a.ndim)

1


In [28]:
b = np.array([[1,2,3],[4,5,6]]) #two dimention
print(b.ndim)

2


In [26]:
print(b)

[[1 2 3]
 [4 5 6]]


In [44]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c.ndim)

3


In [34]:
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [38]:
print(a.shape)

(4,)


In [40]:
print(b.shape)

(2, 3)


In [42]:
print(c.shape)

(2, 2, 2)


 # functions for creating array

In [49]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [55]:
b = np.arange(1,10,2)
print(b)

[1 3 5 7 9]


In [63]:
#using linspace
a = np.linspace(0,1,10)
print(a)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [65]:
a = np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [71]:
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [75]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [100]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [79]:
a = np.eye(3,2)
print(a)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [91]:
a = np.eye(3,6)
print(a)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


In [93]:
a = np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [97]:
print(np.diag(a))

[1 2 3 4]


# BASIC DATA TYPES

In [127]:
a = np.arange(6)
print(a.dtype)

int32


In [131]:
a = np.arange(10, dtype="float64")
print(a.dtype)

float64


In [120]:
a = np.zeros((3,3))
print(a)
print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


# other datatype

In [135]:
a = np.array([1+2j,2+4j])
print(a.dtype)

complex128


In [137]:
a = np.array([True, False])
print(a.dtype)

bool


In [143]:
a = np.array(['Siri','deepu'])
print(a.dtype) #unicode string type = U

<U5


In [147]:
a = np.array(['aditya','degree','college'])
print(a.dtype)

<U7


# INDEXING AND SLICING

In [156]:
a = np.arange(10)
print(a[5])

5


In [158]:
a = np.diag([1,2,3])
print(a[2,2])

3


In [174]:
a[2,1] = 2
print(a)


[[1 0 0]
 [0 5 5]
 [0 2 2]]


# slicing

In [177]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [181]:
a = np.arange(10)
print(a[1:8:2])

[1 3 5 7]


In [195]:
a = np.arange(10)
a[7:]=9
a

array([0, 1, 2, 3, 4, 5, 6, 9, 9, 9])

# copies and viewing

In [202]:
a = np.arange(10)
b = a[::2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [206]:
print(np.shares_memory(a,b))

True


In [212]:
b[0] = 10
print(a)
print(b)

[10  1  2  3  4  5  6  7  8  9]
[10  2  4  6  8]


In [216]:
a = np.arange(10)
b = a[::2].copy()
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [218]:
print(np.shares_memory(a,b))

False


In [220]:
b[0] = 10
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[10  2  4  6  8]


# RANDOM NUMBER GENERATOR

In [232]:
a = np.random.randint(0,20,15) #here "15" represents random number
print(a)

[ 6 11 16  8  5 18 17 11  0 19 15  6  3 14  1  6 17 15 18 10]


In [234]:
mask=(a%4==0)

In [238]:
mask_a = a[mask]
print(mask_a)

[ 6 16  8 18  0  6 14  6 18 10]


In [240]:
a[mask] = -1
print(a)

[-1 11 -1 -1  5 -1 17 11 -1 19 15 -1  3 -1  1 -1 17 15 -1 -1]


# ELEMENT WISE OPERATIONS

In [3]:
import numpy as np
a = np.array([1,2,3,4])
print(a+1) #addd + 1

[2 3 4 5]


In [5]:
print(a**2) # squares

[ 1  4  9 16]


# All Arthimetic Operates Element wise

In [8]:
b = np.ones(4) + 1
print("a = ",a)
print("b = ",b)

a =  [1 2 3 4]
b =  [2. 2. 2. 2.]


In [10]:
print(a*b)

[2. 4. 6. 8.]


In [12]:
print(a-b)

[-1.  0.  1.  2.]


In [14]:
print(a+b)

[3. 4. 5. 6.]


In [16]:
#Matrix multiplication
c = np.diag([1,2,3,4])
print(c)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [20]:
print(c*c)

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


# Comparision Operators

In [25]:
a = np.array([1,2,3,4])
b = np.array([5,2,3,4])
print(a==b)

[False  True  True  True]


In [27]:
print(a>b)

[False False False False]


In [29]:
print(a<b)

[ True False False False]


In [31]:
print(a<=b)

[ True  True  True  True]


In [33]:
print(a>=b)

[False  True  True  True]


In [35]:
#Array wise comparision
a = np.array([1,2,3,4])
b = np.array([5,4,1,2])
c = np.array([1,2,3,4])
print(np.array_equal(a,b))

False


In [37]:
print(np.array_equal(a,c))

True


# Logical Operators

In [40]:
a = np.array([1,0,1,0],dtype = "bool")
b = np.array([1,0,1,0],dtype = "bool")

In [42]:
print(np.logical_or(a,b))

[ True False  True False]


In [44]:
print(np.logical_and(a,b))

[ True False  True False]


In [46]:
print(np.logical_not(a))

[False  True False  True]


# Trigonometry/Transcendental Functions

In [49]:
a = np.array([1,2,3,4])
print(np.sin(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [51]:
print(np.cos(a))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [53]:
print(np.tan(a))

[ 1.55740772 -2.18503986 -0.14254654  1.15782128]


In [55]:
print(np.log(a))

[0.         0.69314718 1.09861229 1.38629436]


In [59]:
print(np.exp(a))

[ 2.71828183  7.3890561  20.08553692 54.59815003]


# Basic Reductions

In [62]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [64]:
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [66]:
a.sum(axis=0)

array([4, 6])

In [68]:
a.sum(axis=1)

array([3, 7])